name: new-relic-exporter
"on":
  workflow_run:
    workflows: ["*"] # This watches all workflows, including the Build & Test workflow
    types:
      - completed
env:
  GHA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  GHA_RUN_ID: ${{ github.event.workflow_run.id }}
  GHA_RUN_NAME: ${{ github.event.workflow_run.name }}
jobs:
  new-relic-exporter:
    name: new-relic-exporter
    runs-on: ubuntu-latest
    if: ${{ always() }} # This ensures it runs even if the watched workflow fails
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: new-relic-exporter
        uses: newrelic-experimental/gha-new-relic-exporter@latest
