name: new-relic-exporter
on:
  workflow_run:
    workflows:
      - "*"
    types:
      - completed
env:
  GHA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  GHA_RUN_ID: ${{ github.event.workflow_run.id }}
  GHA_RUN_NAME: ${{ github.event.workflow_run.name }}
  GHA_DEBUG: ${{ secrets.GHA_DEBUG }}
jobs:
  new-relic-exporter:
    name: new-relic-exporter
    runs-on: ubuntu-latest
    if: ${{ always() }}
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: new-relic-exporter
        uses: newrelic-experimental/gha-new-relic-exporter@latest
